### ISSUE TITLE
Flight status

### ISSUE THREAD

**Issue by BayramAnnakov** [appintheair/aita-widget-sdk-ios#1]
Allow to get flight status to display status-specific widget content

**Comment by spronin** [comment]
You can do that now:
`FlightInfo.dateTakeoff`, `FlightInfo.dateTakeoffUTC`, `FlightInfo.dateLanding`, `FlightInfo.dateLandingUTC` count delay.

Delays are `FlightInfo.departureDelayActual` and `FlightInfo.arrivalDelayActual` in seconds.
